<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Microsoft.CodeAnalysis.BannedApiAnalyzers" Version="3.3.4" />
  </ItemGroup>

  <ItemGroup>
    <GlobalPackageReference Include="MinVer" Version="7.0.0" />
  </ItemGroup>

</Project>
