using Npgsql;

namespace Concertable.Testing.Integration.IntegrationTests;

/// <summary>
/// Stands in for a migrated service database: one owned schema whose table carries an identity column,
/// that schema's migration history, the two shared message-store histories, and the PostGIS metadata a
/// spatial service installs. A reset has to empty the first and leave the rest exactly as they are.
/// </summary>
public sealed class ResetScopeFixture : IAsyncLifetime
{
    public const string OwnedSchema = "owned";
    public const string MessagingSchema = "messaging";

    private readonly PostgresFixture postgres = new();

    public string ConnectionString => postgres.ConnectionString;

    public async Task InitializeAsync()
    {
        await postgres.InitializeAsync();
        await ExecuteAsync($"""
            CREATE EXTENSION IF NOT EXISTS postgis;
            CREATE SCHEMA "{OwnedSchema}";
            CREATE SCHEMA "{MessagingSchema}";
            CREATE TABLE "{OwnedSchema}"."Sentinel" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Name" text NOT NULL);
            CREATE TABLE "{OwnedSchema}"."{OwnedSchemaSelector.MigrationsHistory}" (
                "MigrationId" character varying(150) PRIMARY KEY,
                "ProductVersion" character varying(32) NOT NULL);
            CREATE TABLE "{MessagingSchema}"."{OwnedSchemaSelector.MigrationsHistory}_Inbox" (
                "MigrationId" character varying(150) PRIMARY KEY,
                "ProductVersion" character varying(32) NOT NULL);
            CREATE TABLE "{MessagingSchema}"."{OwnedSchemaSelector.MigrationsHistory}_Outbox" (
                "MigrationId" character varying(150) PRIMARY KEY,
                "ProductVersion" character varying(32) NOT NULL);
            INSERT INTO "{OwnedSchema}"."{OwnedSchemaSelector.MigrationsHistory}" VALUES ('20260101000000_InitialCreate', '10.0.4');
            INSERT INTO "{MessagingSchema}"."{OwnedSchemaSelector.MigrationsHistory}_Inbox" VALUES ('20260101000001_InitialCreate', '10.0.4');
            INSERT INTO "{MessagingSchema}"."{OwnedSchemaSelector.MigrationsHistory}_Outbox" VALUES ('20260101000002_InitialCreate', '10.0.4');
            """);

        await postgres.InitializeRespawnerAsync([OwnedSchema, MessagingSchema]);
    }

    public Task ResetAsync() => postgres.ResetAsync();

    public Task DisposeAsync() => postgres.DisposeAsync();

    public async Task SeedSentinelsAsync(params string[] names)
    {
        var values = string.Join(", ", names.Select(name => $"('{name}')"));
        await ExecuteAsync($"""INSERT INTO "{OwnedSchema}"."Sentinel" ("Name") VALUES {values};""");
    }

    public async Task<long> ScalarAsync(string sql)
    {
        await using var connection = new NpgsqlConnection(ConnectionString);
        await connection.OpenAsync();
        await using var command = connection.CreateCommand();
        command.CommandText = sql;
        return Convert.ToInt64(await command.ExecuteScalarAsync(), System.Globalization.CultureInfo.InvariantCulture);
    }

    private async Task ExecuteAsync(string sql)
    {
        await using var connection = new NpgsqlConnection(ConnectionString);
        await connection.OpenAsync();
        await using var command = connection.CreateCommand();
        command.CommandText = sql;
        await command.ExecuteNonQueryAsync();
    }
}

[CollectionDefinition(Name)]
public sealed class ResetScopeCollection : ICollectionFixture<ResetScopeFixture>
{
    public const string Name = "ResetScope";
}
